-- Simple ACCOUNTS table for savings & transfers
CREATE TABLE ACCOUNTS (
  AccountID NUMBER PRIMARY KEY,
  CustomerID NUMBER,
  Balance NUMBER,
  AccountType VARCHAR2(20) -- e.g., 'SAVINGS', 'CURRENT'
);

-- EMPLOYEES table for bonus scenario
CREATE TABLE EMPLOYEES (
  EmployeeID NUMBER PRIMARY KEY,
  Name VARCHAR2(50),
  DepartmentID NUMBER,
  Salary NUMBER
);

-- Example: Insert some accounts & employees
INSERT INTO ACCOUNTS VALUES (1, 1, 5000, 'SAVINGS');
INSERT INTO ACCOUNTS VALUES (2, 1, 3000, 'CURRENT');
INSERT INTO ACCOUNTS VALUES (3, 2, 7000, 'SAVINGS');

INSERT INTO EMPLOYEES VALUES (101, 'John', 10, 50000);
INSERT INTO EMPLOYEES VALUES (102, 'Alice', 10, 55000);
INSERT INTO EMPLOYEES VALUES (103, 'Bob', 20, 60000);

COMMIT;
/
